services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
    ports:
      - "${APP_PORT:-3000}:3000"
    restart: unless-stopped
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - app_web_node_modules:/app/apps/web/node_modules
      - app_content_node_modules:/app/packages/content/node_modules
      - app_next_cache:/app/apps/web/.next

volumes:
  app_content_node_modules:
  app_next_cache:
  app_node_modules:
  app_web_node_modules:
